### ISSUE TITLE
Problems converting to BJD and HJD...

### ISSUE THREAD

**Issue by gccobservatory** [WarwickAstro/time-conversions#2]
Great tool... except I can't get it to convert my JDs to BJD or HJD (MJD works fine).  Every time I try use the example given in the README I get the following:

python convert_times.py test jd start bjd 10:00:00 -- -20:00:00 lapalma 60
Converting START --> MID
Input times in JD, applying no initial correction
Output set to BJD_TDB_MID, adding barycentric correction
Traceback (most recent call last):
  File "convert_times.py", line 161, in <module>
    ltt_bary, _ = getLightTravelTimes(args.ra, args.dec, time_inp)
  File "convert_times.py", line 96, in getLightTravelTimes
    ltt_bary = time_to_correct.light_travel_time(target, 'barycentric')
  File "/usr/lib/python2.7/dist-packages/astropy/time/core.py", line 1072, in __getattr__
    return self.__getattribute__(attr)
AttributeError: 'Time' object has no attribute 'light_travel_time'

Any ideas what I'm doing wrong?  Also, is there an "easy" way to input a custom observing location into your code?

Thanks

**Comment by jmccormac01** [comment]
Which version of astropy are you using? The light travel time calculations were added relatively recently.

**Comment by gccobservatory** [comment]
Yup that was it.... I was using an old version of astropy.  Thanks for the hint.

**Comment by jmccormac01** [comment]
Great, thanks for confirming. Closing this issue
